#!/usr/bin/env bash
# Paper Translator — Codex installer
#
# Usage:
#   bash codex/install.sh [target-dir]
#
# Copies AGENTS.md and scripts/ into the target directory (default: current
# working directory). The target folder name does not matter — all paths
# are resolved relative to the copied AGENTS.md.
#
# Modes:
#   project  (default) Copy into target directory for project-scoped use
#   global   Register with ~/.codex/config.toml for user-wide use

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
AGENTS_SRC="${SCRIPT_DIR}/AGENTS.md"
SCRIPTS_SRC="${ROOT_DIR}/plugins/paper-translator/scripts"

MODE="${1:-}"
if [ -z "${MODE}" ]; then
  echo "Paper Translator (Codex) — install mode?"
  echo "  [1] project  — copy AGENTS.md + scripts/ into $(pwd)"
  echo "  [2] global   — register with ~/.codex/config.toml"
  read -r -p "choose [1/2]: " choice
  case "${choice}" in
    1|project) MODE=project ;;
    2|global)  MODE=global ;;
    *) echo "[abort] unknown choice: ${choice}"; exit 2 ;;
  esac
fi

echo "[install] paper-translator repository : ${ROOT_DIR}"
echo "[install] scripts source              : ${SCRIPTS_SRC}"
echo "[install] AGENTS.md source            : ${AGENTS_SRC}"
echo "[install] mode                        : ${MODE}"

install_project() {
  local target_dir="${2:-$(pwd)}"
  local target_agents="${target_dir}/AGENTS.md"
  local target_scripts="${target_dir}/scripts"

  if [ -e "${target_agents}" ]; then
    echo "[warn] ${target_agents} already exists"
    read -r -p "  overwrite? [y/N] " ans
    case "${ans}" in
      y|Y|yes|YES) ;;
      *) echo "[abort] keeping existing AGENTS.md"; return 1 ;;
    esac
  fi

  # Copy AGENTS.md
  cp "${AGENTS_SRC}" "${target_agents}"
  echo "[ok] copied AGENTS.md -> ${target_agents}"

  # Copy scripts
  if [ -d "${target_scripts}" ]; then
    echo "[warn] ${target_scripts} already exists, updating..."
    rm -rf "${target_scripts}"
  fi
  cp -r "${SCRIPTS_SRC}" "${target_scripts}"
  echo "[ok] copied scripts/ -> ${target_scripts}"

  # Write env snippet (optional, for manual use)
  local env_file="${target_dir}/.paper-translator.env"
  cat > "${env_file}" <<EOF
# Optional — only needed if you want to override script location.
# Codex uses ./scripts/ relative to AGENTS.md by default.
export PAPER_TRANSLATOR_SCRIPTS="./scripts"
export PYTHONIOENCODING=utf-8
EOF
  echo "[ok] wrote optional env snippet -> ${env_file}"
  echo
  echo "[next] open this folder in VS Code (or any Codex-aware editor) and say:"
  echo "         translate <path-to-pdf>"
  echo "       No env setup is needed — AGENTS.md references ./scripts/ by default."
}

install_global() {
  local codex_dir="${HOME}/.codex"
  local cfg="${codex_dir}/config.toml"
  local instr="${codex_dir}/paper-translator-AGENTS.md"
  local global_scripts="${codex_dir}/paper-translator-scripts"
  mkdir -p "${codex_dir}"

  # Copy AGENTS.md with absolute script path baked in
  {
    cat <<EOF
<!--
  Generated by paper-translator codex/install.sh (global mode)
  Configured paths (Codex should use these literally):
-->

## Configuration

- **Scripts directory**: \`${global_scripts}\`

When any step below says \`\${PAPER_TRANSLATOR_SCRIPTS:-./scripts}\`,
use the absolute path above instead.

---

EOF
    sed "s|\${PAPER_TRANSLATOR_SCRIPTS:-./scripts}|${global_scripts}|g" \
        "${AGENTS_SRC}"
  } > "${instr}"
  echo "[ok] wrote AGENTS.md (paths baked in) -> ${instr}"

  # Copy scripts
  if [ -d "${global_scripts}" ]; then
    rm -rf "${global_scripts}"
  fi
  cp -r "${SCRIPTS_SRC}" "${global_scripts}"
  echo "[ok] copied scripts -> ${global_scripts}"

  # Register in config.toml
  local snippet="# --- paper-translator (auto-added) ---
[[instructions]]
path = \"${instr}\"
# --- /paper-translator ---"

  if [ -f "${cfg}" ] && grep -q "paper-translator (auto-added)" "${cfg}"; then
    echo "[info] already registered in ${cfg}, skipping append"
  else
    printf "\n%s\n" "${snippet}" >> "${cfg}"
    echo "[ok] appended registration to ${cfg}"
  fi

  echo
  echo "[next] Codex will now use Paper Translator globally."
  echo "       Say 'translate <path-to-pdf>' in any project."
}

case "${MODE}" in
  project|1) install_project "$@" ;;
  global|2)  install_global ;;
  *) echo "[error] unknown mode: ${MODE} (use 'project' or 'global')"; exit 2 ;;
esac

echo
echo "[check] Python dependencies"
if python -c "import sys; sys.exit(0 if sys.version_info >= (3,10) else 1)" 2>/dev/null; then
  echo "  Python: $(python --version)"
else
  echo "[error] Python 3.10+ required"
  exit 3
fi

MISSING=()
for pkg in fitz markdown pymdownx; do
  if python -c "import ${pkg}" 2>/dev/null; then
    echo "  ok ${pkg}"
  else
    echo "  !! ${pkg} (missing)"
    case "${pkg}" in
      fitz) MISSING+=("pymupdf") ;;
      pymdownx) MISSING+=("pymdown-extensions") ;;
      *) MISSING+=("${pkg}") ;;
    esac
  fi
done

if [ ${#MISSING[@]} -gt 0 ]; then
  echo
  echo "[next] install missing packages:"
  echo "  pip install ${MISSING[*]}"
fi

echo
command -v pandoc   >/dev/null 2>&1 && echo "  ok pandoc"   || echo "  -- pandoc   (optional, fallback exists)"
command -v lualatex >/dev/null 2>&1 && echo "  ok lualatex" || echo "  -- lualatex (optional, only for PDF output)"
command -v code     >/dev/null 2>&1 && echo "  ok code"     || echo "  -- code     (optional, for VSCode preview)"

echo
echo "[done] Paper Translator (Codex) installed."
